server:
  port: 7002

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: count-service # 路由的id,没有规定规则但要求唯一,建议配合服务名
          uri: lb://count-service
          predicates:
            - Path=/api/count/** # 断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1 #路由时去掉第一个前缀/api


        - id: query-service
          uri: lb://query-service
          predicates:
            - Path=/api/query/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    hostname: eureka
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/