server:
  port: 7002
  servlet:
    context-path: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: count-service # 路由的id,没有规定规则但要求唯一,建议配合服务名
          uri: lb://count-service
          predicates:
            - Path=/api/count-service/** # 断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1

        - id: query-service
          uri: lb://query-service
          predicates:
            - Path=/api/query-service/**
          #去掉/api后再转发请求到相应的服务
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth-service/**
          #去掉/api后再转发请求到相应的服务
          filters:
            - StripPrefix=1

eureka:
  instance:
    instance-id: api-gateway
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔.单位为秒(默认30 秒)
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳等待时间上限.单位为秒(默认90 秒),超时将剔除服务
    lease-expiration-duration-in-seconds: 2
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/